const SUPABASE_URL="https://mqgrvddgmfdebpvozipa.supabase.co";
const SUPABASE_KEY="sb_publishable_gXHAAlDIYLEq6nO-VT1Hag_a7VMElzP";
const APPDATA_TABLE="APP_DATA";
const AUTH_KEY="pointage_auth_v4_staging";
const LOCAL_KEY="australia_team_app_v2_staging";
const PROFILE_KEY="australia_team_profile_v2_staging";
const TEAM_NS="teamAppV2Staging";
const EMPLOYEES=[
 {id:"jb",name:"JB",admin:true},{id:"louella",name:"Louella",admin:false},{id:"gillou",name:"Gillou",admin:false},{id:"cyril",name:"Cyril",admin:false},{id:"chloe",name:"Chloé",admin:false},{id:"caro",name:"Caro",admin:false},{id:"ingrid",name:"Ingrid",admin:true},{id:"coco",name:"Coco",admin:true}
];
let state=null,profileId=localStorage.getItem(PROFILE_KEY)||"",adminUnlockedUntil=0,pinBuffer="",pinPurpose="unlock",publicWeek=startOfWeek(new Date()),adminWeek=startOfWeek(new Date()),saveTimer=null,cloudBusy=false,sortables=[];
const $=id=>document.getElementById(id),pad=n=>String(n).padStart(2,"0"),dayKey=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,hm=d=>`${pad(d.getHours())}:${pad(d.getMinutes())}`,clone=x=>JSON.parse(JSON.stringify(x));
function startOfWeek(d){const x=new Date(d);x.setHours(12,0,0,0);x.setDate(x.getDate()-((x.getDay()+6)%7));return x}
function weekKey(d){return dayKey(startOfWeek(d))}
function fmtDate(ds,opts={weekday:"short",day:"numeric",month:"short"}){return new Date(ds+"T12:00:00").toLocaleDateString("fr-FR",opts)}
function employee(id){return EMPLOYEES.find(x=>x.id===id)||null}
function currentProfile(){return employee(profileId)}
function toast(t){const e=$("toast");e.textContent=t;e.classList.remove("hidden");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add("hidden"),2200)}
function defaultState(){return{version:1,updatedAt:new Date().toISOString(),employees:EMPLOYEES,adminPinHash:"",sessions:[],drafts:{},published:{},weekExtras:{},audit:[]}}
function normalizeState(s){const d=defaultState(),x=s&&typeof s==="object"?s:{};return{...d,...x,employees:EMPLOYEES,sessions:Array.isArray(x.sessions)?x.sessions:[],drafts:x.drafts&&typeof x.drafts==="object"?x.drafts:{},published:x.published&&typeof x.published==="object"?x.published:{},weekExtras:x.weekExtras&&typeof x.weekExtras==="object"?x.weekExtras:{},audit:Array.isArray(x.audit)?x.audit:[]}}
function loadLocal(){try{state=normalizeState(JSON.parse(localStorage.getItem(LOCAL_KEY)||"null"))}catch{state=defaultState()}return state}
function saveLocal(){state.updatedAt=new Date().toISOString();localStorage.setItem(LOCAL_KEY,JSON.stringify(state))}
function audit(action,detail=""){state.audit.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),by:currentProfile()?.name||"?",action,detail});state.audit=state.audit.slice(0,300)}
function getSession(){try{return JSON.parse(localStorage.getItem(AUTH_KEY)||"null")}catch{return null}}
function saveSession(s){localStorage.setItem(AUTH_KEY,JSON.stringify(s))}
function userId(){return getSession()?.user?.id||null}
async function authRequest(path,body){const r=await fetch(`${SUPABASE_URL}/auth/v1/${path}`,{method:"POST",headers:{apikey:SUPABASE_KEY,"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.msg||j.message||j.error_description||"Connexion impossible");return j}
async function ensureSession(){let s=getSession();if(!s)return null;if(!s.expires_at||s.expires_at-Date.now()<60000){if(!navigator.onLine)return s;try{const j=await authRequest("token?grant_type=refresh_token",{refresh_token:s.refresh_token});s={access_token:j.access_token,refresh_token:j.refresh_token,expires_at:Date.now()+((j.expires_in||3600)*1000),user:j.user||s.user};saveSession(s)}catch{return null}}return s}
async function appFetch(path="",options={}){const s=await ensureSession();if(!s)throw new Error("Connexion expirée");const headers={apikey:SUPABASE_KEY,"Content-Type":"application/json",Prefer:options.prefer||"return=representation",Authorization:`Bearer ${s.access_token}`,...(options.headers||{})};const r=await fetch(`${SUPABASE_URL}/rest/v1/${APPDATA_TABLE}${path}`,{...options,headers});if(!r.ok)throw new Error((await r.text())||`Erreur ${r.status}`);if(r.status===204)return[];const t=await r.text();return t?JSON.parse(t):[]}
async function loadCloud(){if(!navigator.onLine||!userId()){setSync("Mode hors connexion","err");return false}try{setSync("Synchronisation…");const rows=await appFetch(`?select=payload,updated_at&user_id=eq.${encodeURIComponent(userId())}&limit=1`);if(rows[0]?.payload?.[TEAM_NS]){const cloud=normalizeState(rows[0].payload[TEAM_NS]);if(new Date(cloud.updatedAt||0)>=new Date(state.updatedAt||0)){state=cloud;saveLocal()}}else{await saveCloudNow()}setSync("Synchronisé","ok");renderAll();return true}catch(e){console.warn(e);setSync("Sauvegarde locale","err");return false}}
async function saveCloudNow(){if(cloudBusy||!navigator.onLine||!userId())return false;cloudBusy=true;try{const rows=await appFetch(`?select=payload&user_id=eq.${encodeURIComponent(userId())}&limit=1`);const payload={...(rows[0]?.payload||{}),[TEAM_NS]:state};await appFetch(`?on_conflict=user_id`,{method:"POST",prefer:"resolution=merge-duplicates,return=representation",body:JSON.stringify({user_id:userId(),payload,updated_at:state.updatedAt})});setSync("Synchronisé","ok");return true}catch(e){console.warn(e);setSync("À synchroniser","err");return false}finally{cloudBusy=false}}
function scheduleSave(){saveLocal();setSync("Enregistrement…");clearTimeout(saveTimer);saveTimer=setTimeout(saveCloudNow,650)}
function setSync(text,cls=""){const e=$("syncStatus");e.textContent=text;e.className=cls?`sync ${cls}`:"sync"}
function openDrawer(){$("drawer").classList.add("open");$("backdrop").classList.add("open")}
function closeDrawer(){$("drawer").classList.remove("open");$("backdrop").classList.remove("open")}
function showView(name){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===`view-${name}`));document.querySelectorAll(".navBtn,.menuItem[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===name));const titles={home:"Accueil",point:"Pointer",planning:"Planning",hours:"Mes heures",recap:"Récap mensuel",planningAdmin:"Créer planning",corrections:"Corriger pointages",audit:"Historique"};$("topTitle").textContent=titles[name]||"Australia Street";closeDrawer();if(name==="planning")renderPublicPlanning();if(name==="hours")renderHours();if(name==="recap")renderRecap();if(name==="planningAdmin")renderAdminPlanning();if(name==="corrections")renderCorrections();if(name==="audit")renderAudit()}
function setupMenus(){document.querySelectorAll("[data-view]").forEach(b=>b.addEventListener("click",()=>showView(b.dataset.view)));document.querySelectorAll("[data-view-jump]").forEach(b=>b.addEventListener("click",()=>showView(b.dataset.viewJump)));document.querySelectorAll("[data-admin]").forEach(b=>b.addEventListener("click",()=>requireAdmin(()=>showView(b.dataset.admin))));$("menuBtn").onclick=openDrawer;$("backdrop").onclick=closeDrawer;$("profileBtn").onclick=openDrawer;$("switchProfile").onclick=()=>{localStorage.removeItem(PROFILE_KEY);profileId="";closeDrawer();showProfileScreen()}}
function showProfileScreen(){const g=$("profileGrid");g.innerHTML=EMPLOYEES.map(e=>`<button class="profileBtn ${e.admin?'admin':''}" data-profile="${e.id}">${e.name}</button>`).join("");g.querySelectorAll("button").forEach(b=>b.onclick=()=>{profileId=b.dataset.profile;localStorage.setItem(PROFILE_KEY,profileId);$("profileScreen").classList.add("hidden");startApp()});$("profileScreen").classList.remove("hidden")}
async function login(){const email=$("authEmail").value.trim(),password=$("authPassword").value;if(!email||password.length<8){$("authMsg").textContent="Entre l’email et le mot de passe de l’accès équipe.";return}$("authBtn").disabled=true;try{const j=await authRequest("token?grant_type=password",{email,password});saveSession({access_token:j.access_token,refresh_token:j.refresh_token,expires_at:Date.now()+((j.expires_in||3600)*1000),user:j.user});$("auth").classList.add("hidden");await loadCloud();if(profileId)startApp();else showProfileScreen()}catch(e){$("authMsg").textContent=e.message}finally{$("authBtn").disabled=false}}
function currentOpenSession(empId=profileId){return state.sessions.filter(s=>s.employeeId===empId&&!s.stop).sort((a,b)=>b.start.localeCompare(a.start))[0]||null}
function sessionStatus(empId=profileId){const s=currentOpenSession(empId);if(!s)return"none";const p=s.pauses?.at(-1);if(p&&!p.end)return"pause";return"work"}
function totalSessionMs(s,live=false){if(!s?.start)return 0;let end=s.stop?new Date(s.stop).getTime():(live?Date.now():new Date(s.start).getTime()),total=end-new Date(s.start).getTime();for(const p of s.pauses||[]){const pe=p.end?new Date(p.end).getTime():(live?Date.now():end);total-=Math.max(0,pe-new Date(p.start).getTime())}return Math.max(0,total)}
function fmtMs(ms){const m=Math.floor(Math.max(0,ms)/60000);return`${Math.floor(m/60)}h${pad(m%60)}`}