(()=>{
const ADM=new Set(['jb','coco','ingrid']);
async function rpc(n,b={}){const s=await ensureSession();if(!s)throw new Error('Session expirée');const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${n}`,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'},body:JSON.stringify(b)});const t=await r.text();if(!r.ok)throw new Error(t||`Erreur ${r.status}`);return t?JSON.parse(t):null}
function allowed(){const p=currentProfile();return !!(p?.admin&&ADM.has(String(profileId||'').toLowerCase()))}
async function okFor(cb){adminUnlockedUntil=Date.now()+9*60*1000;closeModal();try{if(typeof window.refreshAdminData==='function')await window.refreshAdminData()}catch(e){console.error(e)}cb()}
function setup(cb){openModal(`<div class="modal light"><div class="modalHead"><b>Créer mon PIN administrateur</b><button class="closeBtn" data-close>✕</button></div><div class="pageSub">PIN personnel de ${escapeHtml(currentProfile()?.name||'Admin')}. Il doit être différent du code de connexion.</div><label>Code personnel de connexion</label><input id="secLogin" type="password" maxlength="64"><label style="margin-top:10px">PIN admin</label><input id="secPin" type="password" inputmode="numeric" maxlength="12"><label style="margin-top:10px">Confirmer</label><input id="secPin2" type="password" inputmode="numeric" maxlength="12"><div class="modalActions"><button class="smallBtn" data-close>Annuler</button><button class="smallBtn light" id="secSave">Enregistrer</button></div><div id="secMsg" class="sync" style="text-align:center"></div></div>`);$('secSave').onclick=async()=>{const a=$('secLogin').value,p=$('secPin').value,p2=$('secPin2').value,m=$('secMsg');if(a.length<8){m.textContent='Entre ton code de connexion.';return}if(!/^\d{8,12}$/.test(p)){m.textContent='PIN admin: 8 à 12 chiffres.';return}if(p!==p2){m.textContent='Les PIN ne correspondent pas.';return}if(p===a){m.textContent='Choisis un PIN admin différent.';return}const btn=$('secSave');btn.disabled=true;try{const x=await rpc('team_set_admin_pin',{login_code:a,pin:p});if(x!=='ok'){const map={invalid_login:'Code de connexion incorrect.',invalid_pin:'PIN admin invalide.',pin_unavailable:'Ce PIN est déjà utilisé.',old_pin_required:'Ancien PIN admin requis.'};throw new Error(map[x]||'Impossible d’enregistrer le PIN.')}if(await rpc('team_unlock_admin',{code:p})!==true)throw new Error('Déverrouillage impossible.');await okFor(cb)}catch(e){m.textContent=e.message||'Erreur'}finally{btn.disabled=false}}}
function unlock(cb){openModal(`<div class="modal light"><div class="modalHead"><b>PIN administrateur</b><button class="closeBtn" data-close>✕</button></div><div class="pageSub">PIN personnel de ${escapeHtml(currentProfile()?.name||'Admin')}. Après 5 erreurs, blocage 15 minutes.</div><label>PIN admin</label><input id="secUnlock" type="password" inputmode="numeric" maxlength="12"><div class="modalActions"><button class="smallBtn" data-close>Annuler</button><button class="smallBtn light" id="secUnlockBtn">Déverrouiller</button></div><div id="secMsg" class="sync" style="text-align:center"></div></div>`);$('secUnlockBtn').onclick=async()=>{const p=$('secUnlock').value,m=$('secMsg'),btn=$('secUnlockBtn');if(!/^\d{8,12}$/.test(p)){m.textContent='Entre ton PIN admin.';return}btn.disabled=true;try{if(await rpc('team_unlock_admin',{code:p})!==true){m.textContent='PIN incorrect ou accès temporairement bloqué.';return}await okFor(cb)}catch(e){m.textContent=e.message||'Erreur'}finally{btn.disabled=false}}}
window.requireAdmin=async function(cb){if(!allowed()){toast('Accès réservé à JB, Coco et Ingrid');return}try{if(await rpc('team_is_admin',{})===true){adminUnlockedUntil=Date.now()+9*60*1000;try{if(typeof window.refreshAdminData==='function')await window.refreshAdminData()}catch(e){console.error(e)}cb();return}if(await rpc('team_admin_pin_configured',{})===true)unlock(cb);else setup(cb)}catch(e){toast(e.message||'Accès administrateur impossible')}};
window.openPinModal=cb=>window.requireAdmin(cb);
})();