function act(type){const emp=currentProfile();if(!emp)return;const st=sessionStatus();let s=currentOpenSession();if(type==="start"&&st==="none"){state.sessions.push({id:crypto.randomUUID(),employeeId:emp.id,start:new Date().toISOString(),stop:null,pauses:[],note:"",createdAt:new Date().toISOString()});toast("Arrivée enregistrée")}
 else if(type==="pause"&&st==="work"){s.pauses.push({start:new Date().toISOString(),end:null});toast("Pause enregistrée")}
 else if(type==="resume"&&st==="pause"){s.pauses.at(-1).end=new Date().toISOString();toast("Reprise enregistrée")}
 else if(type==="stop"&&(st==="work"||st==="pause")){if(st==="pause")s.pauses.at(-1).end=new Date().toISOString();s.stop=new Date().toISOString();toast("Départ enregistré")}else return;state.updatedAt=new Date().toISOString();scheduleSave();renderAll()}
function todaySessions(empId=profileId){const ds=dayKey(new Date());return state.sessions.filter(s=>s.employeeId===empId&&dayKey(new Date(s.start))===ds).sort((a,b)=>a.start.localeCompare(b.start))}
function sessionsForEmployee(empId){return state.sessions.filter(s=>s.employeeId===empId).sort((a,b)=>b.start.localeCompare(a.start))}
function renderPointing(){const st=sessionStatus(),labels={none:"Pas encore pointé",work:"En poste",pause:"En pause"};$("homeState").textContent=labels[st];$("pointState").textContent=labels[st];$("startBtn").disabled=st!=="none";$("pauseBtn").disabled=st!=="work";$("resumeBtn").disabled=st!=="pause";$("stopBtn").disabled=st==="none";const main=$("homeMainAction");main.textContent=st==="none"?"POINTER MON ARRIVÉE":st==="pause"?"REPRENDRE":"POINTER MON DÉPART";main.onclick=()=>act(st==="none"?"start":st==="pause"?"resume":"stop");const td=todaySessions();$("todayDetail").innerHTML=td.length?td.map(s=>sessionRow(s,true)).join(""):'<div class="empty">Aucun pointage aujourd’hui.</div>';const recent=sessionsForEmployee(profileId).slice(0,5);$("homeHistory").innerHTML=recent.length?recent.map(s=>sessionRow(s,false)).join(""):'<div class="empty">Aucun pointage enregistré.</div>';renderHomeNext()}
function sessionRow(s,live){const d=new Date(s.start),parts=[`Arrivée ${hm(d)}`];for(const p of s.pauses||[])parts.push(`pause ${hm(new Date(p.start))}${p.end?` à ${hm(new Date(p.end))}`:""}`);parts.push(s.stop?`départ ${hm(new Date(s.stop))}`:"en cours");return`<div class="listRow"><div class="listMain"><b>${d.toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'})}</b><small>${parts.join(' · ')}</small></div><div class="listValue">${fmtMs(totalSessionMs(s,live))}</div></div>`}
function publishedWeekData(wk){return state.published[wk]?.days||{}}
function renderHomeNext(){const wk=weekKey(new Date()),days=publishedWeekData(wk),ds=dayKey(new Date()),items=days[ds]||[],mine=items.filter(x=>x.employeeId===profileId);$("homeNext").textContent=mine.length?mine.map(x=>`${displayRange(x)}`).join(" · "):"Aucun horaire publié aujourd’hui"}
function displayRange(x){const a=x.startMode==="open"?"Ouverture":x.start||"";const b=x.endMode==="close"?"Fermeture":x.endMode==="kitchen"?"Fin cuisine":x.end||"";return`${a} → ${b}`}
function weekLabelText(d){const s=startOfWeek(d),e=new Date(s);e.setDate(e.getDate()+6);return`Du ${s.toLocaleDateString('fr-FR',{day:'numeric',month:'short'})} au ${e.toLocaleDateString('fr-FR',{day:'numeric',month:'short',year:'numeric'})}`}
function renderPublicPlanning(){$("publicWeekLabel").textContent=weekLabelText(publicWeek);const wk=weekKey(publicWeek),pub=state.published[wk],days=pub?.days||{};let html="";for(let i=0;i<7;i++){const d=new Date(publicWeek);d.setDate(d.getDate()+i);const ds=dayKey(d),items=days[ds]||[];html+=`<div class="dayBlock"><div class="dayHead"><div><b>${d.toLocaleDateString('fr-FR',{weekday:'long'}).toUpperCase()}</b><span>${d.toLocaleDateString('fr-FR',{day:'numeric',month:'long'})}</span></div>${pub?'<span class="publishedBadge">PUBLIÉ</span>':''}</div><div class="dayList">${items.length?items.map(publicShiftCard).join(''):'<div class="dropHint">Aucune personne planifiée</div>'}</div></div>`}$("publicPlanning").innerHTML=html}
function publicShiftCard(x){return`<div class="shiftCard" style="cursor:default"><div><div class="shiftName">${escapeHtml(x.name)}</div><div class="shiftMeta">${x.isExtra?'Extra':'Équipe'}</div></div><div class="shiftTime">${escapeHtml(displayRange(x))}</div><div></div></div>`}
function draftFor(wk){if(!state.drafts[wk])state.drafts[wk]={days:{},updatedAt:new Date().toISOString()};return state.drafts[wk]}
function extrasFor(wk){if(!state.weekExtras[wk])state.weekExtras[wk]=[];return state.weekExtras[wk]}
function renderAdminPlanning(){if(Date.now()>adminUnlockedUntil){requireAdmin(()=>renderAdminPlanning());return}const wk=weekKey(adminWeek),draft=draftFor(wk);$("adminWeekLabel").textContent=weekLabelText(adminWeek);let html="";for(let i=0;i<7;i++){const d=new Date(adminWeek);d.setDate(d.getDate()+i);const ds=dayKey(d),items=draft.days[ds]||[];html+=`<div class="dayBlock"><div class="dayHead"><div><b>${d.toLocaleDateString('fr-FR',{weekday:'long'}).toUpperCase()}</b><span>${d.toLocaleDateString('fr-FR',{day:'numeric',month:'long'})}</span></div></div><div class="dayList adminDrop" data-date="${ds}">${items.length?items.map(adminShiftCard).join(''):'<div class="dropHint">Glisse un prénom ici</div>'}</div></div>`}$("adminPlanning").innerHTML=html;$("peoplePalette").innerHTML=EMPLOYEES.map(e=>`<button class="personChip" data-person="${e.id}" data-name="${escapeHtml(e.name)}">${escapeHtml(e.name)}</button>`).join('');$("extrasPalette").innerHTML=extrasFor(wk).map(e=>`<button class="personChip extraChip" data-person="${e.id}" data-name="${escapeHtml(e.name)}" data-extra="1">${escapeHtml(e.name)}</button>`).join('');initSortables()}
function adminShiftCard(x){return`<div class="shiftCard" data-assignment="${x.id}"><div><div class="shiftName">${escapeHtml(x.name)}</div><div class="shiftMeta">${x.isExtra?'Extra':'Équipe'}</div></div><div class="shiftTime">${escapeHtml(displayRange(x))}</div><button class="shiftEdit" data-edit-shift="${x.id}">⋮</button></div>`}
function destroySortables(){sortables.forEach(s=>{try{s.destroy()}catch{}});sortables=[]}
function initSortables(){destroySortables();if(typeof Sortable==="undefined")return;const paletteOpts={group:{name:"team",pull:"clone",put:false},sort:false,animation:150,delay:120,delayOnTouchOnly:true};sortables.push(new Sortable($("peoplePalette"),paletteOpts));sortables.push(new Sortable($("extrasPalette"),paletteOpts));document.querySelectorAll(".adminDrop").forEach(el=>sortables.push(new Sortable(el,{group:"team",animation:160,delay:100,delayOnTouchOnly:true,onAdd:e=>handleDrop(e),onEnd:e=>handleMove(e)})));document.querySelectorAll("[data-edit-shift]").forEach(b=>b.onclick=e=>{e.stopPropagation();openShiftEditor(b.dataset.editShift)})}
function findAssignment(id){const wk=weekKey(adminWeek),draft=draftFor(wk);for(const [date,items] of Object.entries(draft.days)){const x=items.find(a=>a.id===id);if(x)return{date,item:x,items}}return null}
function handleDrop(e){const toDate=e.to.dataset.date,fromPalette=e.from.id==="peoplePalette"||e.from.id==="extrasPalette";if(fromPalette){const id=e.item.dataset.person,name=e.item.dataset.name,isExtra=e.item.dataset.extra==="1";e.item.remove();const draft=draftFor(weekKey(adminWeek));if(!draft.days[toDate])draft.days[toDate]=[];draft.days[toDate].push({id:crypto.randomUUID(),employeeId:isExtra?null:id,name,isExtra,startMode:"time",start:"18:00",endMode:"close",end:"",note:""});audit("Planning modifié",`${name} ajouté le ${fmtDate(toDate)}`);scheduleSave();renderAdminPlanning()}else handleMove(e)}
function handleMove(e){const id=e.item.dataset.assignment;if(!id)return;const found=findAssignment(id);if(!found)return;const to=e.to.dataset.date;if(found.date===to)return;found.items.splice(found.items.indexOf(found.item),1);const draft=draftFor(weekKey(adminWeek));if(!draft.days[to])draft.days[to]=[];draft.days[to].push(found.item);audit("Planning modifié",`${found.item.name} déplacé vers ${fmtDate(to)}`);scheduleSave();renderAdminPlanning()}