function addManualSession(){openModal(`<div class="modal"><div class="modalHead"><b>Ajouter une journée</b><button class="closeBtn" data-close>✕</button></div><div class="formGrid"><div class="full"><label>Personne</label><select id="newEmp">${EMPLOYEES.map(e=>`<option value="${e.id}">${e.name}</option>`).join('')}</select></div><div class="full"><label>Date</label><input id="newDate" type="date" value="${dayKey(new Date())}"></div><div><label>Arrivée</label><input id="newStart" type="time"></div><div><label>Départ</label><input id="newStop" type="time"></div><div class="full"><label>Note</label><input id="newNote"></div></div><div class="modalActions"><button class="smallBtn" data-close>Annuler</button><button id="saveNewSession" class="smallBtn light">Ajouter</button></div></div>`);$("newEmp").value=$("correctionEmployee").value||"jb";$("saveNewSession").onclick=()=>{const emp=$("newEmp").value,date=$("newDate").value,st=$("newStart").value,sp=$("newStop").value;if(!date||!st){toast("Date et arrivée obligatoires");return}state.sessions.push({id:crypto.randomUUID(),employeeId:emp,start:new Date(`${date}T${st}:00`).toISOString(),stop:sp?endIso(date,st,sp):null,pauses:[],note:$("newNote").value.trim(),createdAt:new Date().toISOString()});audit("Pointage ajouté",`${employee(emp)?.name} · ${fmtDate(date)} ${st}${sp?' à '+sp:''}`);scheduleSave();closeModal();renderCorrections();renderAll()}}
function renderCorrections(){if(Date.now()>adminUnlockedUntil)return;const sel=$("correctionEmployee");if(!sel.options.length)sel.innerHTML=EMPLOYEES.map(e=>`<option value="${e.id}">${e.name}</option>`).join('');const empId=sel.value||"jb",rows=sessionsForEmployee(empId).slice(0,60);$("correctionList").innerHTML=rows.length?rows.map(s=>`<div class="listRow"><div class="listMain"><b>${fmtDate(dayKey(new Date(s.start)),{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</b><small>Arrivée ${hm(new Date(s.start))}${s.stop?` · départ ${hm(new Date(s.stop))}`:' · journée en cours'} · ${fmtMs(totalSessionMs(s,false))}</small></div><button class="smallBtn" data-edit-session="${s.id}">Modifier</button></div>`).join(''):'<div class="empty">Aucun pointage pour cette personne.</div>';document.querySelectorAll("[data-edit-session]").forEach(b=>b.onclick=()=>editSessionModal(b.dataset.editSession))}
function sessionsInMonth(empId,y,m){return state.sessions.filter(s=>s.employeeId===empId&&new Date(s.start).getFullYear()===y&&new Date(s.start).getMonth()===m)}
function renderHours(){const now=new Date(),rows=sessionsInMonth(profileId,now.getFullYear(),now.getMonth()).sort((a,b)=>b.start.localeCompare(a.start)),total=rows.reduce((a,s)=>a+totalSessionMs(s,false),0),days=new Set(rows.map(s=>dayKey(new Date(s.start)))).size;$("hoursMetrics").innerHTML=`<div class="metric"><b>${fmtMs(total)}</b><span>CE MOIS</span></div><div class="metric"><b>${days}</b><span>JOURS POINTÉS</span></div>`;$("hoursList").innerHTML=rows.length?rows.map(s=>sessionRow(s,false)).join(''):'<div class="empty">Aucune heure ce mois-ci.</div>'}
function buildMonthOptions(){const set=new Set();state.sessions.filter(s=>s.employeeId===profileId).forEach(s=>{const d=new Date(s.start);set.add(`${d.getFullYear()}-${pad(d.getMonth()+1)}`)});const n=new Date();set.add(`${n.getFullYear()}-${pad(n.getMonth()+1)}`);return[...set].sort().reverse()}
function renderRecap(){const select=$("recapMonth"),cur=select.value;select.innerHTML=buildMonthOptions().map(k=>{const[y,m]=k.split('-').map(Number);return`<option value="${k}">${new Date(y,m-1,1).toLocaleDateString('fr-FR',{month:'long',year:'numeric'})}</option>`}).join('');if(cur&&[...select.options].some(o=>o.value===cur))select.value=cur;const k=select.value;if(!k)return;const[y,m]=k.split('-').map(Number),rows=sessionsInMonth(profileId,y,m-1).sort((a,b)=>a.start.localeCompare(b.start)),total=rows.reduce((a,s)=>a+totalSessionMs(s,false),0),days=new Set(rows.map(s=>dayKey(new Date(s.start)))).size;$("recapMetrics").innerHTML=`<div class="metric"><b>${fmtMs(total)}</b><span>TOTAL RÉEL</span></div><div class="metric"><b>${days}</b><span>JOURS</span></div>`;$("recapList").innerHTML=rows.length?rows.map(s=>sessionRow(s,false)).join(''):'<div class="empty">Aucune heure pour ce mois.</div>'}
function recapRows(){const k=$("recapMonth").value,[y,m]=k.split('-').map(Number);return sessionsInMonth(profileId,y,m-1).sort((a,b)=>a.start.localeCompare(b.start))}
function downloadCSV(){const rows=recapRows();if(!rows.length){toast("Aucune heure à exporter");return}const lines=[["Date","Arrivée","Départ","Total"],...rows.map(s=>[dayKey(new Date(s.start)),hm(new Date(s.start)),s.stop?hm(new Date(s.stop)):"",fmtMs(totalSessionMs(s,false))])];const csv=lines.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n'),blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'});downloadBlob(blob,`recap-${profileId}-${$("recapMonth").value}.csv`)}
function downloadPDF(){const rows=recapRows();if(!rows.length){toast("Aucune heure à exporter");return}if(!window.jspdf?.jsPDF){toast("PDF indisponible");return}const {jsPDF}=window.jspdf,doc=new jsPDF({unit:'mm',format:'a4'}),p=currentProfile(),k=$("recapMonth").value;let y=18;doc.setFont('helvetica','bold');doc.setFontSize(18);doc.text('AUSTRALIA STREET - RECAP HEURES',15,y);y+=9;doc.setFontSize(12);doc.text(`${p.name} - ${k}`,15,y);y+=10;let total=0;doc.setFontSize(9);for(const s of rows){if(y>275){doc.addPage();y=18}const ms=totalSessionMs(s,false);total+=ms;doc.setFont('helvetica','bold');doc.text(fmtDate(dayKey(new Date(s.start)),{day:'2-digit',month:'2-digit',year:'numeric'}),15,y);doc.setFont('helvetica','normal');doc.text(`Arrivee ${hm(new Date(s.start))} - Depart ${s.stop?hm(new Date(s.stop)):'-'}`,48,y);doc.setFont('helvetica','bold');doc.text(fmtMs(ms),165,y);y+=7}y+=5;doc.line(15,y,195,y);y+=8;doc.setFontSize(12);doc.text(`TOTAL : ${fmtMs(total)}`,15,y);doc.save(`recap-${profileId}-${k}.pdf`)}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1200)}
function renderAudit(){if(Date.now()>adminUnlockedUntil)return;$("auditList").innerHTML=state.audit.length?state.audit.slice(0,100).map(a=>`<div class="listRow"><div class="listMain"><b>${escapeHtml(a.action)}</b><small>${new Date(a.at).toLocaleString('fr-FR')} · ${escapeHtml(a.by)}${a.detail?` · ${escapeHtml(a.detail)}`:''}</small></div></div>`).join(''):'<div class="empty">Aucune modification administrative.</div>'}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function escapeAttr(s){return escapeHtml(s).replace(/`/g,'&#96;')}
function renderAll(){const p=currentProfile();if(!p)return;$("helloName").textContent=`Bonjour ${p.name}`;$("drawerName").textContent=p.name;$("drawerRole").textContent=p.admin?"Administrateur · accès PIN":"Membre de l’équipe";$("adminMenuGroup").classList.toggle("hidden",!p.admin);renderPointing();renderPublicPlanning();renderHours();renderRecap();if(Date.now()<adminUnlockedUntil){renderCorrections();renderAudit()}}
function tick(){const t=hm(new Date());if($("homeClock"))$("homeClock").textContent=t;if($("pointClock"))$("pointClock").textContent=t}
function startApp(){$("app").classList.remove("hidden");const p=currentProfile();if(!p){showProfileScreen();return}renderAll();tick();setInterval(tick,1000);setInterval(()=>{if(document.visibilityState==="visible")loadCloud()},20000)}
async function boot(){loadLocal();setupMenus();$("authBtn").onclick=login;$("enterBtn").onclick=async()=>{$("splash").classList.add("hidden");const s=await ensureSession();if(!s){$("auth").classList.remove("hidden");return}await loadCloud();if(profileId)startApp();else showProfileScreen()};$("startBtn").onclick=()=>act('start');$("pauseBtn").onclick=()=>act('pause');$("resumeBtn").onclick=()=>act('resume');$("stopBtn").onclick=()=>act('stop');document.querySelectorAll("[data-week]").forEach(b=>b.onclick=()=>{publicWeek.setDate(publicWeek.getDate()+Number(b.dataset.week)*7);renderPublicPlanning()});document.querySelectorAll("[data-admin-week]").forEach(b=>b.onclick=()=>{adminWeek.setDate(adminWeek.getDate()+Number(b.dataset.adminWeek)*7);renderAdminPlanning()});$("copyWeekBtn").onclick=copyPreviousWeek;$("addExtraBtn").onclick=addExtra;$("publishBtn").onclick=publishWeek;$("saveDraftBtn").onclick=()=>{scheduleSave();toast("Brouillon enregistré")};$("correctionEmployee").onchange=renderCorrections;$("addManualBtn").onclick=addManualSession;$("recapMonth").onchange=renderRecap;$("csvBtn").onclick=downloadCSV;$("pdfBtn").onclick=downloadPDF;if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
boot();